trigger:
  - none
parameters:
  - name: environment
    displayName: Which Team to deploy?
    type: string
    default: 'Dev'
    values:
    - Dev
    - Uat
    - Prod
 
variables:
  - name: Dev-Tomcat-Path
    ${{ if eq( parameters['environment'], 'Dev') }}:
      value: "/home/test/tomcat"
    ${{ if eq( parameters['environment'], 'Uat' ) }}:
      value: "/home/test/mcat"
    ${{ if notIn( parameters['environment'], 'Dev', 'Uat') }}:
      value: "/home/test/toat"
      
stages:
  - stage: Stage_TomcatStop
    variables:
      tomcatpath: $(Dev-Tomcat-Path)
    jobs:
      - deployment: Tomcat_Stop
        environment:
          name: Test-New
          resourceType: VirtualMachine
          tags: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Killing Tomcat service..."
                    PID=$(pgrep -f "/home/test/tomcat")
                    echo $PID
                    if [ -n "$PID" ]; then
                      echo $PID
                      echo "test" | sudo -S su - test | kill -9 $PID
                      whoami
                      echo "Tomcat service has been killed."
                      exit 0
                    else
                      echo "Tomcat service is not running."
                      exit 1
                    fi
      - job: manual_approval
        dependsOn: Tomcat_Stop
        displayName: Manual Approval
        pool: server
        timeoutInMinutes: 4320
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 360
            inputs:
              notifyUsers: |
              instructions: Hi, Please Confirm Before Launching The Tomcat Service.
              onTimeout: reject
  - stage: Stage_TomcatStart
    variables:
      tomcatpath: $(Dev-Tomcat-Path)
    jobs:
      - deployment: Tomcat_Start
        environment:
          name: Test-New
          resourceType: VirtualMachine
          tags: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Starting Tomcat..."
                    echo $(tomcatpath)
                    cat $(tomcatpath)/bin/startup.sh
                    whoami
                    echo "test" | sudo -S su - test $(tomcatpath)/bin/startup.sh
                    whoami